name: Label target branch

on:
  pull_request:
    branches: [ "opened", "reopened" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
